apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: andel-ambulance-ufe-content
spec:
  microFrontend: andel-ambulance-ufe
  element: andel-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?andel-ambulance-wl(/.*)?$"